/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppLoading: typeof import('./components/AppLoading.vue')['default']
    AppWelcome: typeof import('./components/AppWelcome.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInForm: typeof import('./components/SignInForm.vue')['default']
    SignUpForm: typeof import('./components/SignUpForm.vue')['default']
  }
}
