name: Application

on:
  push:
    branches: 
      - "main"
      - "develop"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Set target directory
        id: set-target-dir
        run: echo "target_dir=${{ github.ref == 'refs/heads/main' && secrets.PROD_TARGET_DIR || secrets.DEV_TARGET_DIR }}" >> $GITHUB_ENV

      - name: Copy files to host
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: ${{ env.target_dir }}

      - name: Update the Frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ env.target_dir }}/app
            npm install
            npm run build

      - name: Update the Backend
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ env.target_dir }}/api
            composer install
            php artisan key:generate
            supervisorctl restart "nospend-worker:*"
