name: Application

on:
  push:
    branches: 
      - "main"
      - "develop"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Set target directory
        id: set-target-dir
        run: echo "target_dir=${{ github.ref == 'refs/heads/main' && secrets.PROD_TARGET_DIR || secrets.DEV_TARGET_DIR }}" >> $GITHUB_ENV

      - name: Update files on host
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ env.target_dir }}
            if [ ! -d ".git" ]; then
              git clone --branch ${{ github.ref_name }} https://oauth2:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} .
            else
              git reset --hard
              git clean -fd
              git pull origin ${{ github.ref_name }}
            fi

      - name: Update the Frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ env.target_dir }}/app
            npm install
            npm run build

      - name: Update the Backend
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ env.target_dir }}/api
            composer install
            php artisan key:generate
            supervisorctl restart "nospend-worker:*"
